# fly.toml app configuration file generated for crop-compass-server on 2024-10-05T11:04:22+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'crop-compass-server'
primary_region = 'cdg'

[build]

[env]
  AI_RECOMMENDATION_API = 'https://crop-compass-ai.onrender.com'
  EARTHDATA_TOKEN = 'eyJ0eXAiOiJKV1QiLCJvcmlnaW4iOiJFYXJ0aGRhdGEgTG9naW4iLCJzaWciOiJlZGxqd3RwdWJrZXlfb3BzIiwiYWxnIjoiUlMyNTYifQ.eyJ0eXBlIjoiVXNlciIsInVpZCI6ImF5bWFueWFzc2VyIiwiZXhwIjoxNzMzMjI2NTU1LCJpYXQiOjE3MjgwNDI1NTUsImlzcyI6Imh0dHBzOi8vdXJzLmVhcnRoZGF0YS5uYXNhLmdvdiJ9.K3H0ZenyCx5sOjjKMymSGHKMjdXCXSRmC8bCPLzyeITaZJg4TM-TZK1zCxN6H76dnVflh-fNaDZdUPGA0qiokRhUmgXec1R5fs8ocNH-GHhVDiArRDPOFeqx2V6X3x_NAcy8C9KE8KRcKITHHvMk4eR9iXMV2RLXq4vaZQ3wLa3CNFxnN4dOzYCzsjU6_YdM__5ssAxJF_x0K9v4rK0qerDuK7ORo5mGdlcGGDaQ2JDt9fwEJOFB_vU3V-qagDoRz_rvW5WX3Jvclq1kUnuNc-qiL_G1wn0Egg2DeJB62YI6YQxz2GwBZDiALjjjK_x2jmW_3FqKuxta4XtolZwIKQ'
  GEMINI_API_KEY = 'AIzaSyD7P9ErY19xSfs1GHmPcJmZgPewe_IXJqE'
  MONGODB_URI = 'mongodb+srv://aymanyasser:fZqw1tlVzL4VE6at@cluster0.05umo.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'
  NODE_ENV = 'development'
  SECRET_KEY = 'b4880f3f65ef4b1a7415f96dab24c843c5fca6fc7692ccac7f9f085d334aaf8f2c4c2b8ef4'
  WEATHER_API_KEY = '7XD6NMGXWYFX7E2X7K46LKW55'

[http_service]
  internal_port = 3300
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"  
  cpus = 1  
